const demoCases = [{ caseNumber: 'JC-20260902-A1B2C3', sellerName: '陳小姐', itemCount: 2, status: 'submitted' }, { caseNumber: 'JC-20260901-C8D2E1', sellerName: '林先生', itemCount: 4, status: 'received' }];
let cases = demoCases;
const api = window.JiangnanAdminApi;
const rows = document.querySelector('#rows'); const dialog = document.querySelector('#dialog'); const toast = document.querySelector('.toast'); const state = document.querySelector('[data-connection-state]');
const names = { submitted: '送件', received: '收件', listed: '上架', returned: '退還', cancelled: '取消' };
function render() { rows.innerHTML = cases.map(item => `<tr><td><b>${item.caseNumber}</b></td><td>${item.sellerName}</td><td>${item.itemCount}</td><td><span class="status ${item.status === 'listed' ? 'live' : item.status === 'received' ? 'scheduled' : ''}">${names[item.status] || item.status}</span></td><td><button class="actions" aria-label="案件操作">⋮</button></td></tr>`).join(''); }
function message(value) { toast.textContent = value; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
async function refresh() { cases = await api.listConsignments(); render(); }
render(); document.querySelector('#open').onclick = () => dialog.showModal();
document.querySelector('#form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { sellerName: form.get('name'), sellerContact: form.get('contact'), items: [{ cardName: form.get('card'), cardNumber: null, cardCondition: form.get('condition'), suggestedPriceCents: Number(form.get('price')) }] }; try { if (api.enabled) { await api.createConsignment(input); await refresh(); state.textContent = '已連線正式 API：案件建立與狀態均受伺服器流程限制。'; state.classList.add('connected'); message('寄售案件已建立。'); } else { cases.unshift({ caseNumber: 'JC-展示資料', sellerName: input.sellerName, itemCount: 1, status: 'submitted' }); render(); message('展示資料案件已建立。'); } dialog.close(); event.currentTarget.reset(); } catch (error) { message(error.message || '案件建立失敗。'); } };
if (api.enabled) refresh().then(() => { state.textContent = '已連線正式 API：寄售案件依 OIDC 權限讀取。'; state.classList.add('connected'); }).catch(error => { state.textContent = `無法連線正式 API：${error.message}`; state.classList.add('failed'); });
