const demoCases = [{ caseNumber: 'JC-20260902-A1B2C3', sellerName: '陳小姐', itemCount: 2, status: 'submitted' }, { caseNumber: 'JC-20260901-C8D2E1', sellerName: '林先生', itemCount: 4, status: 'received' }];
let cases = demoCases;
const api = window.JiangnanAdminApi;
const rows = document.querySelector('#rows'); const dialog = document.querySelector('#dialog'); const toast = document.querySelector('.toast'); const state = document.querySelector('[data-connection-state]');
const names = { submitted: '送件', received: '收件', listed: '上架', returned: '退還', cancelled: '取消' };
const transitions = { submitted: [{ status: 'received', label: '確認收件' }, { status: 'cancelled', label: '取消案件' }], received: [{ status: 'listed', label: '標記上架' }, { status: 'returned', label: '退還寄售人' }], listed: [{ status: 'returned', label: '退還寄售人' }] };
function render() { rows.innerHTML = cases.map(item => { const actions = (transitions[item.status] || []).map(action => `<button class="ghost" data-id="${item.id || item.caseNumber}" data-next="${action.status}">${action.label}</button>`).join(''); return `<tr><td><b>${item.caseNumber}</b></td><td>${item.sellerName}</td><td>${item.itemCount}</td><td><span class="status ${item.status === 'listed' ? 'live' : item.status === 'received' ? 'scheduled' : ''}">${names[item.status] || item.status}</span></td><td class="case-actions">${actions || '<small>無可執行操作</small>'}</td></tr>`; }).join(''); }
function message(value) { toast.textContent = value; toast.classList.add('show'); setTimeout(() => toast.classList.remove('show'), 2600); }
async function refresh() { cases = await api.listConsignments(); render(); }
render(); document.querySelector('#open').onclick = () => dialog.showModal();
document.querySelector('#form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const input = { sellerName: form.get('name'), sellerContact: form.get('contact'), items: [{ cardName: form.get('card'), cardNumber: null, cardCondition: form.get('condition'), suggestedPriceCents: Number(form.get('price')) }] }; try { if (api.enabled) { await api.createConsignment(input); await refresh(); state.textContent = '已連線正式 API：案件建立與狀態均受伺服器流程限制。'; state.classList.add('connected'); message('寄售案件已建立。'); } else { cases.unshift({ caseNumber: 'JC-展示資料', sellerName: input.sellerName, itemCount: 1, status: 'submitted' }); render(); message('展示資料案件已建立。'); } dialog.close(); event.currentTarget.reset(); } catch (error) { message(error.message || '案件建立失敗。'); } };
if (api.enabled) refresh().then(() => { state.textContent = '已連線正式 API：寄售案件依 OIDC 權限讀取。'; state.classList.add('connected'); }).catch(error => { state.textContent = `無法連線正式 API：${error.message}`; state.classList.add('failed'); });
rows.addEventListener('click', async event => { const id = event.target.dataset.id; const next = event.target.dataset.next; if (!id || !next) return; try { if (api.enabled) { await api.updateConsignmentStatus(id, next); await refresh(); state.textContent = '已連線正式 API：狀態變更已由伺服器流程驗證。'; state.classList.add('connected'); } else { cases = cases.map(item => (item.id || item.caseNumber) === id ? { ...item, status: next } : item); render(); } message(`案件已更新為「${names[next]}」。`); } catch (error) { message(error.message || '案件狀態更新失敗。'); } });
