const demoContent = [{ title: '九月會員日：卡牌周邊 9 折', kind: 'promotion', startsAt: '2026-09-01', endsAt: '2026-09-30', status: 'published' }, { title: '寶可夢卡牌交流賽', kind: 'event', startsAt: '2026-09-06', endsAt: null, status: 'published' }];
let posts = demoContent;
const rows = document.querySelector('#rows'), dialog = document.querySelector('#dialog'), toast = document.querySelector('.toast'), api = window.JiangnanAdminApi, state = document.querySelector('[data-connection-state]');
const names = { event: '活動', notice: '公告', promotion: '優惠' }; const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c])); const date = value => value ? new Date(value).toLocaleDateString('zh-TW').replaceAll('/', '.') : '未排程';
function render() { rows.innerHTML = posts.map(post => `<tr><td><b>${esc(post.title)}</b></td><td>${names[post.kind] || post.kind}</td><td>${date(post.startsAt)}${post.endsAt ? ` - ${date(post.endsAt)}` : ''}</td><td><span class="status ${post.status === 'published' ? 'live' : ''}">${post.status === 'published' ? '發布中' : '草稿'}</span></td></tr>`).join(''); }
function message(value) { toast.textContent = value; toast.classList.add('show'); clearTimeout(message.timeout); message.timeout = setTimeout(() => toast.classList.remove('show'), 2600); }
async function refresh() { posts = await api.listContent(); render(); }
render(); document.querySelector('#open').onclick = () => dialog.showModal();
document.querySelector('#form').onsubmit = async event => { event.preventDefault(); const form = new FormData(event.currentTarget); const asIso = value => value ? new Date(value).toISOString() : null; const input = { slug: form.get('slug'), kind: form.get('kind'), title: form.get('title'), summary: form.get('summary'), body: form.get('body'), startsAt: asIso(form.get('startsAt')), endsAt: asIso(form.get('endsAt')), status: form.get('status') }; try { if (api.enabled) { await api.createContent(input); await refresh(); state.textContent = '已連線正式 API：內容已依 OIDC 權限儲存。'; state.classList.add('connected'); message('內容已儲存。'); } else { posts.unshift(input); render(); message('展示資料內容已儲存。'); } dialog.close(); event.currentTarget.reset(); } catch (error) { message(error.message || '內容儲存失敗。'); } };
if (api.enabled) refresh().then(() => { state.textContent = '已連線正式 API：內容資料依 OIDC 權限讀取。'; state.classList.add('connected'); }).catch(error => { state.textContent = `無法連線正式 API：${error.message}`; state.classList.add('failed'); });
