const demoProducts = [{ id: 'demo-preorder-001', sku: 'PK-SV-BOX-001', name: '寶可夢 SV 系列擴充包 BOX', kind: 'preorder', priceCents: 1490, depositCents: 745, releaseDate: '2026-12-01', status: 'published' }, { id: 'demo-instock-001', sku: 'PK-RANDOM-001', name: '寶可夢隨機卡包組', kind: 'in_stock', priceCents: 680, availableStock: 24, status: 'published' }];
let products = demoProducts;
let editingProductId = null;
let session = null;
let rejectingProductId = null;
const table = document.querySelector('#product-table');
const dialog = document.querySelector('#product-dialog');
const toast = document.querySelector('.toast');
const api = window.JiangnanAdminApi;
const state = document.querySelector('[data-connection-state]');
const money = value => `NT$ ${Number(value).toLocaleString('zh-TW')}`;
const esc = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
function message(value) { toast.textContent = value; toast.classList.add('show'); clearTimeout(message.timeout); message.timeout = setTimeout(() => toast.classList.remove('show'), 2600); }
function render() { table.innerHTML = products.map(p => { const pending = p.status === 'pending_review' || p.pendingChangeId; const ownerId = p.pendingChangeId ? p.pendingChangeCreatedById : p.createdById; const ownPending = pending && ownerId === session?.id; const actions = !api.enabled ? `<button class="ghost" data-edit="${p.id}">編輯</button>` : `<button class="ghost" data-history="${p.id}">歷程</button>${session?.permissions.includes('product:write') ? `<button class="ghost" data-edit="${p.id}">編輯</button>` : ''}${ownPending && session?.permissions.includes('product:write') ? `<button class="ghost" data-cancel="${p.id}">撤回</button>` : ''}${pending && !ownPending && session?.permissions.includes('product:approve') ? `<button class="ghost" data-approve="${p.id}">核准</button><button class="ghost" data-reject="${p.id}">駁回</button>` : ''}`; return `<tr><td><b>${esc(p.name)}</b><small> ${esc(p.sku)}</small></td><td>${p.kind === 'preorder' ? '預購' : '現貨'}</td><td>${p.originalPriceCents ? `<small style="text-decoration:line-through">${money(p.originalPriceCents)}</small><br>` : ''}<b>${money(p.priceCents)}</b>${p.pendingChangeId ? `<small class="pending-price">待審：${p.pendingOriginalPriceCents ? `${money(p.pendingOriginalPriceCents)} → ` : ''}${money(p.pendingPriceCents)}</small>` : ''}</td><td>${p.kind === 'preorder' ? `訂金 ${money(p.depositCents)} ・ ${esc(String(p.releaseDate).slice(0, 10))} 到貨` : `可售 ${p.availableStock} 件`}</td><td><span class="status ${p.status === 'published' ? 'live' : p.status === 'pending_review' ? 'review' : ''}">${p.status === 'published' ? '上架' : p.status === 'pending_review' ? '待審核' : p.status === 'archived' ? '已封存' : '草稿'}</span>${p.pendingChangeId ? '<small class="review-note">調價待審</small>' : ''}</td><td class="product-actions">${actions}</td></tr>`; }).join(''); }
async function refresh() { [products, session] = await Promise.all([api.listProducts(), api.session()]); render(); }
render();
document.querySelector('[name="price"]').closest('label').insertAdjacentHTML('afterend','<label>原價（NT$）<input name="originalPrice" type="number" min="0" placeholder="無折扣請留空"></label>');
function setKindFields(kind) { const preorder = kind === 'preorder'; document.querySelector('#deposit-field').hidden = !preorder; document.querySelector('#release-field').hidden = !preorder; document.querySelector('#stock-field').hidden = preorder; }
function openNewProduct() { editingProductId = null; document.querySelector('#product-dialog-eyebrow').textContent = 'NEW PRODUCT'; document.querySelector('#product-dialog-title').textContent = '新增商品'; document.querySelector('#product-form').reset(); setKindFields('preorder'); dialog.showModal(); }
document.querySelectorAll('#open-product,#open-product-2').forEach(button => button.addEventListener('click', openNewProduct));
document.querySelector('#product-kind').addEventListener('change', event => setKindFields(event.target.value));
document.querySelector('#product-form').addEventListener('submit', async event => {
  event.preventDefault(); const form = new FormData(event.currentTarget); const preorder = form.get('kind') === 'preorder';
  const input = { sku: form.get('sku'), name: form.get('name'), kind: form.get('kind'), priceCents: Number(form.get('price')), originalPriceCents: form.get('originalPrice') ? Number(form.get('originalPrice')) : null, depositCents: preorder ? Number(form.get('deposit')) : null, availableStock: preorder ? null : Number(form.get('stock')), releaseDate: preorder ? form.get('releaseDate') : null, imageUrl: null, status: form.get('status') };
  try {
    if (api.enabled) { const result = editingProductId ? await api.updateProduct(editingProductId, input) : await api.createProduct(input); await refresh(); state.textContent = '已連線正式 API：商品資料依 OIDC 權限讀取與寫入。'; state.classList.add('connected'); message(result.pendingChangeId || result.status === 'pending_review' ? '商品價格已送交審核。' : '商品已由正式 API 儲存。'); }
    else { if (editingProductId) products = products.map(p => p.id === editingProductId ? { ...p, ...input } : p); else products.unshift(input); render(); message('展示資料已儲存。'); }
    dialog.close(); event.currentTarget.reset();
  } catch (error) { message(error.message || '商品儲存失敗。'); }
});
if (api.enabled) refresh().then(() => { state.textContent = '已連線正式 API：商品資料依 OIDC 權限讀取。'; state.classList.add('connected'); }).catch(error => { state.textContent = `無法連線正式 API：${error.message}`; state.classList.add('failed'); });
table.addEventListener('click', async event => { const id = event.target.dataset.edit || event.target.dataset.approve || event.target.dataset.reject || event.target.dataset.cancel || event.target.dataset.history; if (!id) return; if (event.target.dataset.history) { try { const rows = await api.productChangeHistory(id); const list = document.querySelector('#history-list'); list.innerHTML = rows.length ? rows.map(row => `<article><b>${row.status === 'approved' ? '已核准' : row.status === 'rejected' ? '已駁回' : row.status === 'cancelled' ? '已撤回' : '待審核'}</b><span>${row.originalPriceCents ? `${money(row.originalPriceCents)} → ` : ''}${money(row.priceCents)}</span><small>提出：${esc(row.createdBy)}・${new Date(row.createdAt).toLocaleString('zh-TW')}</small>${row.reviewedAt ? `<small>處理：${esc(row.reviewedBy)}・${new Date(row.reviewedAt).toLocaleString('zh-TW')}</small>` : ''}${row.reviewNote ? `<p>${esc(row.reviewNote)}</p>` : ''}</article>`).join('') : '<p class="empty-history">尚無調價審核紀錄。</p>'; document.querySelector('#history-dialog').showModal(); } catch (error) { message(error.message || '讀取審核歷程失敗。'); } return; } if (event.target.dataset.edit) { const p = products.find(item => item.id === id); if (!p) return message('找不到商品資料，請重新整理後再試。'); editingProductId = id; document.querySelector('#product-dialog-eyebrow').textContent = 'PRODUCT EDIT'; document.querySelector('#product-dialog-title').textContent = '編輯商品'; const form = document.querySelector('#product-form'); form.name.value = p.name; form.sku.value = p.sku; form.kind.value = p.kind; form.price.value = p.priceCents; form.originalPrice.value = p.originalPriceCents ?? ''; form.deposit.value = p.depositCents ?? ''; form.stock.value = p.availableStock ?? ''; form.releaseDate.value = p.releaseDate ? String(p.releaseDate).slice(0, 10) : ''; form.status.value = p.status === 'pending_review' ? 'draft' : p.status; setKindFields(p.kind); dialog.showModal(); return; } if (event.target.dataset.reject) { rejectingProductId = id; document.querySelector('#reject-form').reset(); document.querySelector('#reject-dialog').showModal(); return; } try { if (event.target.dataset.cancel) { await api.cancelProductChange(id); message('待審變更已撤回。'); } else { await api.approveProduct(id); message('商品價格與上架狀態已核准。'); } await refresh(); } catch (error) { message(error.message || '商品操作失敗。'); } });
document.querySelector('#reject-form').addEventListener('submit', async event => { event.preventDefault(); const reviewNote = new FormData(event.currentTarget).get('reviewNote'); try { await api.rejectProduct(rejectingProductId, reviewNote); await refresh(); document.querySelector('#reject-dialog').close(); message('商品變更已駁回。'); } catch (error) { message(error.message || '商品駁回失敗。'); } });
