import cors from 'cors';
import express from 'express';
import { verifyOidcAccessToken } from './auth.js';
import { createBannerUpload, inspectBannerUpload, validateBannerUpload, writeLocalBannerUpload } from './storage.js';
import pg from 'pg';
import { z } from 'zod';

const app = express();
const pool = new pg.Pool({ connectionString: process.env.DATABASE_URL });
const roles = { admin: ['banner:view','banner:create','banner:submit','banner:approve','banner:disable','product:view','product:write','product:approve','content:view','content:write','consignment:view','consignment:write','order:view','user:view','audit:view'], content_editor: ['banner:view','banner:create','banner:submit','content:view','content:write'], ad_operator: ['banner:view','banner:create','banner:submit'], product_editor: ['product:view','product:write'], consignment_staff: ['consignment:view','consignment:write'] };
const internalPath = z.string().regex(/^\/[a-zA-Z0-9/_?=&-]*$/);
const targetUrl = z.union([z.string().url(), internalPath]).nullable();
const bannerInput = z.object({ name: z.string().trim().min(1).max(120), kind: z.enum(['store', 'external']), placement: z.enum(['hero', 'home_leaderboard', 'product_sidebar', 'mobile_banner']), priority: z.number().int().min(0).max(1000), startsAt: z.string().datetime(), endsAt: z.string().datetime(), targetUrl, imageKey: z.string().trim().min(1).max(512), imageUrl: z.string().url().nullable().optional() }).refine(value => new Date(value.endsAt) > new Date(value.startsAt), { message: '結束時間必須晚於開始時間', path: ['endsAt'] });
const bannerUploadInput = z.object({ fileName: z.string().trim().min(1).max(180), contentType: z.enum(['image/jpeg', 'image/png', 'image/webp']), contentLength: z.number().int().positive().max(5242880) });
const eventInput = z.object({ eventKey: z.string().uuid() });
const productInput = z.object({ sku: z.string().trim().regex(/^[A-Z0-9-]{3,48}$/), name: z.string().trim().min(1).max(160), kind: z.enum(['preorder', 'in_stock']), priceCents: z.number().int().nonnegative(), originalPriceCents: z.number().int().nonnegative().nullable(), depositCents: z.number().int().nonnegative().nullable(), availableStock: z.number().int().nonnegative().nullable(), releaseDate: z.string().date().nullable(), imageUrl: z.string().url().nullable(), status: z.enum(['draft', 'pending_review', 'published', 'archived']) }).superRefine((value, ctx) => { if (value.originalPriceCents !== null && value.originalPriceCents < value.priceCents) ctx.addIssue({ code: 'custom', message: '原價不可低於活動售價。' }); if (value.kind === 'preorder' && (value.depositCents === null || value.releaseDate === null)) ctx.addIssue({ code: 'custom', message: '預購商品必須有訂金與到貨日。' }); if (value.kind === 'in_stock' && value.availableStock === null) ctx.addIssue({ code: 'custom', message: '現貨商品必須有庫存。' }); });
const reviewInput = z.object({ reviewNote: z.string().trim().min(1).max(400) });
const contentInput = z.object({ slug:z.string().regex(/^[a-z0-9-]{3,100}$/),kind:z.enum(['event','notice','promotion']),title:z.string().trim().min(1).max(160),summary:z.string().trim().min(1).max(300),body:z.string().max(20000),startsAt:z.string().datetime().nullable(),endsAt:z.string().datetime().nullable(),status:z.enum(['draft','published','archived']) }).refine(v=>!v.startsAt||!v.endsAt||new Date(v.endsAt)>new Date(v.startsAt),{message:'結束時間必須晚於開始時間',path:['endsAt']});
const consignmentInput=z.object({sellerName:z.string().trim().min(1).max(80),sellerContact:z.string().trim().min(1).max(160),items:z.array(z.object({cardName:z.string().trim().min(1).max(160),cardNumber:z.string().trim().max(80).nullable(),cardCondition:z.string().trim().min(1).max(80),suggestedPriceCents:z.number().int().nonnegative()})).min(1).max(100)});
const publicConsignmentInput=z.object({sellerName:z.string().trim().min(1).max(80),sellerContact:z.string().trim().min(1).max(160),cardDescription:z.string().trim().min(1).max(1000),privacyConsent:z.literal(true),privacyVersion:z.string().trim().regex(/^[A-Za-z0-9._-]{1,32}$/)});
const checkoutInput=z.object({idempotencyKey:z.string().uuid(),customerEmail:z.string().email().max(254),items:z.array(z.object({productId:z.string().uuid(),quantity:z.number().int().min(1).max(10)})).min(1).max(20)});
const publicSubmissionAttempts = new Map();

app.disable('x-powered-by');
app.use((_req,res,next) => { res.setHeader('X-Content-Type-Options','nosniff'); res.setHeader('Referrer-Policy','strict-origin-when-cross-origin'); res.setHeader('X-Frame-Options','DENY'); res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()'); if (process.env.NODE_ENV === 'production') res.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains'); next(); });
app.use(cors({ origin: process.env.PUBLIC_ORIGIN?.split(',') ?? false }));
if (process.env.ASSET_STORAGE_PROVIDER === 'local') app.use('/api/v1/public/banner-assets', express.static(process.env.ASSET_LOCAL_DIRECTORY));
app.put('/api/v1/internal/local-banner-uploads/:token', express.raw({ type: ['image/jpeg', 'image/png', 'image/webp'], limit: '5mb' }), async (req,res,next) => { try { await writeLocalBannerUpload(req.params.token, req.body, req.header('content-type')); res.sendStatus(204); } catch (error) { next(error); } });
app.use(express.json({ limit: '128kb' }));
app.get('/health', async (_req, res) => { await pool.query('SELECT 1'); res.json({ status: 'ok' }); });
app.get('/api/v1/public/banners/:placement', async (req, res, next) => {
  try { const placement = z.enum(['hero', 'home_leaderboard', 'product_sidebar', 'mobile_banner']).parse(req.params.placement); const { rows } = await pool.query('SELECT id,name,kind,target_url AS "targetUrl",image_url AS "imageUrl" FROM active_banner_for_placement($1,now())', [placement]); res.json({ data: rows }); } catch (error) { next(error); }
});
app.post('/api/v1/public/banners/:id/events/:type', async (req, res, next) => {
  try { const { eventKey } = eventInput.parse(req.body); const eventType = z.enum(['impression', 'click']).parse(req.params.type); await pool.query('INSERT INTO banner_events (banner_id,event_type,event_key) VALUES ($1,$2,$3) ON CONFLICT (event_type,event_key) DO NOTHING', [req.params.id, eventType, eventKey]); res.status(202).json({ accepted: true }); } catch (error) { next(error); }
});
app.post('/api/v1/admin/banner-assets/upload-intents',requirePermission('banner:create'),async(req,res,next)=>{const client=await pool.connect();try{const input=bannerUploadInput.parse(req.body);validateBannerUpload(input);const upload=await createBannerUpload(input);await client.query('BEGIN');const{rows}=await client.query(`INSERT INTO banner_assets(object_key,public_url,content_type,size_bytes,created_by) VALUES($1,$2,$3,$4,$5) RETURNING id,object_key AS "imageKey",public_url AS "imageUrl",status`,[upload.objectKey,upload.publicUrl,input.contentType,input.contentLength,req.user.id]);await audit(req.user.id,'banner_asset.upload_intended','banner_asset',rows[0].id,{imageKey:upload.objectKey},client);await client.query('COMMIT');res.status(201).json({data:{...rows[0],uploadUrl:upload.uploadUrl}});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.post('/api/v1/admin/banner-assets/:id/complete',requirePermission('banner:create'),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const asset=await client.query(`SELECT id,object_key,content_type,size_bytes FROM banner_assets WHERE id=$1 AND created_by=$2 AND status='uploading' FOR UPDATE`,[req.params.id,req.user.id]);if(!asset.rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'找不到可驗證的 Banner 素材。'});}const metadata=await inspectBannerUpload(asset.rows[0].object_key);const valid=metadata.contentType===asset.rows[0].content_type&&Number(metadata.sizeBytes)===asset.rows[0].size_bytes;if(!valid){await client.query(`UPDATE banner_assets SET status='rejected',completed_at=now() WHERE id=$1`,[asset.rows[0].id]);await client.query('COMMIT');return res.status(409).json({error:'上傳素材的類型或大小與申請不符。'});}const{rows}=await client.query(`UPDATE banner_assets SET status='uploaded',completed_at=now() WHERE id=$1 RETURNING id,object_key AS "imageKey",public_url AS "imageUrl",status`,[asset.rows[0].id]);await audit(req.user.id,'banner_asset.uploaded','banner_asset',rows[0].id,{imageKey:rows[0].imageKey},client);await client.query('COMMIT');res.json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.post('/api/v1/checkout/intents',async(req,res,next)=>{const client=await pool.connect();try{const input=checkoutInput.parse(req.body);await client.query('BEGIN');const existing=await client.query(`SELECT id,order_number AS "orderNumber",status,amount_due_cents AS "amountDueCents",expires_at AS "expiresAt" FROM orders WHERE idempotency_key=$1`,[input.idempotencyKey]);if(existing.rows[0]){await client.query('COMMIT');return res.json({data:existing.rows[0]});}let due=0;const lines=[];for(const item of input.items){const p=await client.query(`SELECT id,name,kind,price_cents,deposit_cents,available_stock,status FROM products WHERE id=$1 FOR UPDATE`,[item.productId]);const product=p.rows[0];if(!product||product.status!=='published')throw Object.assign(new Error('商品不存在或未上架。'),{status:409});if(product.kind==='in_stock'){const update=await client.query(`UPDATE products SET available_stock=available_stock-$2 WHERE id=$1 AND available_stock >= $2 RETURNING available_stock`,[product.id,item.quantity]);if(!update.rows[0])throw Object.assign(new Error(`庫存不足：${product.name}`),{status:409});}const duePerUnit=product.kind==='preorder'?product.deposit_cents:product.price_cents;due+=duePerUnit*item.quantity;lines.push({product,quantity:item.quantity,duePerUnit,reservedStock:product.kind==='in_stock'});}const number=`JC-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const order=await client.query(`INSERT INTO orders(order_number,idempotency_key,customer_email,amount_due_cents,expires_at) VALUES($1,$2,$3,$4,$5) RETURNING id,order_number AS "orderNumber",status,amount_due_cents AS "amountDueCents",expires_at AS "expiresAt"`,[number,input.idempotencyKey,input.customerEmail,due,orderIntentExpiresAt()]);for(const l of lines)await client.query(`INSERT INTO order_items(order_id,product_id,quantity,product_name,unit_price_cents,due_per_unit_cents,reserved_stock) VALUES($1,$2,$3,$4,$5,$6,$7)`,[order.rows[0].id,l.product.id,l.quantity,l.product.name,l.product.price_cents,l.duePerUnit,l.reservedStock]);await client.query('COMMIT');res.status(201).json({data:order.rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.post('/api/v1/internal/orders/release-expired',async(req,res,next)=>{try{if(!process.env.ORDER_EXPIRY_TOKEN||req.header('x-order-expiry-token')!==process.env.ORDER_EXPIRY_TOKEN)throw Object.assign(new Error('未授權的訂單到期作業。'),{status:401});if(!process.env.ORDER_EXPIRY_ACTOR_ID)throw Object.assign(new Error('訂單到期稽核帳號尚未設定。'),{status:503});res.json({data:await releaseExpiredOrders(process.env.ORDER_EXPIRY_ACTOR_ID)});}catch(error){next(error);}});
app.get('/api/v1/admin/orders',requirePermission('order:view'),async(_req,res,next)=>{try{const{rows}=await pool.query(`SELECT o.order_number AS "orderNumber",regexp_replace(o.customer_email,'^(.).+(@.*)$','\\1***\\2') AS "customerEmail",o.status,o.amount_due_cents AS "amountDueCents",count(i.id)::int AS "itemCount",o.created_at AS "createdAt",o.expires_at AS "expiresAt" FROM orders o LEFT JOIN order_items i ON i.order_id=o.id GROUP BY o.id ORDER BY o.created_at DESC`);res.json({data:rows});}catch(e){next(e);}});
app.get('/api/v1/admin/users',requirePermission('user:view'),async(_req,res,next)=>{try{const{rows}=await pool.query(`SELECT id,display_name AS "displayName",regexp_replace(email,'^(.).+(@.*)$','\\1***\\2') AS email,role,created_at AS "createdAt" FROM users ORDER BY created_at`);res.json({data:rows});}catch(e){next(e);}});
app.get('/api/v1/admin/audit-log',requirePermission('audit:view'),async(_req,res,next)=>{try{const{rows}=await pool.query(`SELECT a.id,a.action,a.entity_type AS "entityType",u.display_name AS actor,a.created_at AS "createdAt" FROM audit_log a JOIN users u ON u.id=a.actor_id ORDER BY a.id DESC LIMIT 100`);res.json({data:rows});}catch(e){next(e);}});
app.get('/api/v1/admin/session',requirePermission('product:view'),async(req,res)=>res.json({data:{id:req.user.id,role:req.user.role,permissions:req.user.permissions}}));
app.get('/api/v1/admin/consignments',requirePermission('consignment:view'),async(_req,res,next)=>{try{const{rows}=await pool.query(`SELECT c.id,c.case_number AS "caseNumber",c.seller_name AS "sellerName",c.status,count(i.id)::int AS "itemCount" FROM consignment_cases c LEFT JOIN consignment_items i ON i.case_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`);res.json({data:rows});}catch(e){next(e);}});
app.post('/api/v1/admin/consignments',requirePermission('consignment:write'),async(req,res,next)=>{const client=await pool.connect();try{const v=consignmentInput.parse(req.body);await client.query('BEGIN');const number=`JC-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const{rows}=await client.query(`INSERT INTO consignment_cases(case_number,seller_name,seller_contact,created_by) VALUES($1,$2,$3,$4) RETURNING id,case_number AS "caseNumber",status`,[number,v.sellerName,v.sellerContact,req.user.id]);for(const i of v.items)await client.query(`INSERT INTO consignment_items(case_id,card_name,card_number,card_condition,suggested_price_cents) VALUES($1,$2,$3,$4,$5)`,[rows[0].id,i.cardName,i.cardNumber,i.cardCondition,i.suggestedPriceCents]);await audit(req.user.id,'consignment.created','consignment',rows[0].id,{itemCount:v.items.length},client);await client.query('COMMIT');res.status(201).json({data:rows[0]});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});
app.post('/api/v1/admin/consignments/:id/status',requirePermission('consignment:write'),async(req,res,next)=>{const client=await pool.connect();try{const nextStatus=z.enum(['received','listed','returned','cancelled']).parse(req.body.status);const allowed={submitted:['received','cancelled'],received:['listed','returned'],listed:['returned']};await client.query('BEGIN');const {rows}=await client.query(`UPDATE consignment_cases SET status=$2 WHERE id=$1 AND status=ANY($3::consignment_case_status[]) RETURNING id,status`,[req.params.id,nextStatus,Object.entries(allowed).filter(([,v])=>v.includes(nextStatus)).map(([k])=>k)]);if(!rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'不允許的寄售狀態變更。'});}await audit(req.user.id,'consignment.status_changed','consignment',rows[0].id,{status:nextStatus},client);await client.query('COMMIT');res.json({data:rows[0]});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});
app.post('/api/v1/public/consignment-requests',async(req,res,next)=>{const client=await pool.connect();try{if(!allowPublicConsignment(req.ip))throw Object.assign(new Error('寄售預約送出過於頻繁，請稍後再試。'),{status:429});const v=publicConsignmentInput.parse(req.body);await client.query('BEGIN');const number=`JC-${new Date().toISOString().slice(0,10).replaceAll('-','')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;const{rows}=await client.query(`INSERT INTO consignment_cases(case_number,seller_name,seller_contact,created_by) VALUES($1,$2,$3,$4) RETURNING id,case_number AS "caseNumber",status`,[number,v.sellerName,v.sellerContact,'00000000-0000-0000-0000-000000000006']);await client.query(`INSERT INTO consignment_items(case_id,card_name,card_condition,suggested_price_cents) VALUES($1,$2,'待鑑定',0)`,[rows[0].id,v.cardDescription]);await audit('00000000-0000-0000-0000-000000000006','consignment.public_submitted','consignment',rows[0].id,{privacyVersion:v.privacyVersion},client);await client.query('COMMIT');res.status(201).json({data:rows[0]});}catch(e){await client.query('ROLLBACK');next(e);}finally{client.release();}});
app.get('/api/v1/public/content/:slug', async (req,res,next)=>{try{const slug=z.string().regex(/^[a-z0-9-]{3,100}$/).parse(req.params.slug);const {rows}=await pool.query(`SELECT slug,kind,title,summary,body,starts_at AS "startsAt",ends_at AS "endsAt" FROM content_posts WHERE slug=$1 AND status='published' AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now())`,[slug]);if(!rows[0])return res.sendStatus(404);res.json({data:rows[0]});}catch(error){next(error);}});
app.get('/api/v1/public/content', async (_req,res,next)=>{try{const {rows}=await pool.query(`SELECT slug,kind,title,summary,starts_at AS "startsAt",ends_at AS "endsAt" FROM content_posts WHERE status='published' AND (starts_at IS NULL OR starts_at<=now()) AND (ends_at IS NULL OR ends_at>now()) ORDER BY starts_at DESC NULLS LAST,created_at DESC`);res.json({data:rows});}catch(error){next(error);}});
app.get('/api/v1/admin/content',requirePermission('content:view'),async(_req,res,next)=>{try{const {rows}=await pool.query(`SELECT id,slug,kind,title,summary,body,starts_at AS "startsAt",ends_at AS "endsAt",status FROM content_posts ORDER BY updated_at DESC`);res.json({data:rows});}catch(error){next(error);}});
app.post('/api/v1/admin/content',requirePermission('content:write'),async(req,res,next)=>{const client=await pool.connect();try{const v=contentInput.parse(req.body);await client.query('BEGIN');const {rows}=await client.query(`INSERT INTO content_posts(slug,kind,title,summary,body,starts_at,ends_at,status,created_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id,status`,[v.slug,v.kind,v.title,v.summary,v.body,v.startsAt,v.endsAt,v.status,req.user.id]);await audit(req.user.id,'content.created','content',rows[0].id,v,client);await client.query('COMMIT');res.status(201).json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.patch('/api/v1/admin/content/:id',requirePermission('content:write'),async(req,res,next)=>{const client=await pool.connect();try{const id=z.string().uuid().parse(req.params.id);const v=contentInput.parse(req.body);await client.query('BEGIN');const{rows}=await client.query(`UPDATE content_posts SET slug=$2,kind=$3,title=$4,summary=$5,body=$6,starts_at=$7,ends_at=$8,status=$9,updated_at=now() WHERE id=$1 RETURNING id,status`,[id,v.slug,v.kind,v.title,v.summary,v.body,v.startsAt,v.endsAt,v.status]);if(!rows[0]){await client.query('ROLLBACK');return res.sendStatus(404);}await audit(req.user.id,'content.updated','content',id,v,client);await client.query('COMMIT');res.json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.get('/api/v1/public/products/:id', async (req, res, next) => { try { const id=z.string().uuid().parse(req.params.id); const { rows } = await pool.query(`SELECT id,sku,name,kind,price_cents AS "priceCents",original_price_cents AS "originalPriceCents",deposit_cents AS "depositCents",available_stock AS "availableStock",release_date AS "releaseDate",image_url AS "imageUrl" FROM products WHERE id=$1 AND status='published'`,[id]); if(!rows[0])return res.sendStatus(404); res.json({ data: rows[0] }); } catch (error) { next(error); } });
app.get('/api/v1/public/products', async (_req, res, next) => { try { const { rows } = await pool.query(`SELECT id,sku,name,kind,price_cents AS "priceCents",original_price_cents AS "originalPriceCents",deposit_cents AS "depositCents",available_stock AS "availableStock",release_date AS "releaseDate",image_url AS "imageUrl" FROM products WHERE status='published' ORDER BY created_at DESC`); res.json({ data: rows }); } catch (error) { next(error); } });
app.get('/api/v1/admin/products', requirePermission('product:view'), async (_req, res, next) => { try { const { rows } = await pool.query(`SELECT p.id,p.sku,p.name,p.kind,p.price_cents AS "priceCents",p.original_price_cents AS "originalPriceCents",p.deposit_cents AS "depositCents",p.available_stock AS "availableStock",p.release_date AS "releaseDate",p.image_url AS "imageUrl",p.status,p.created_by AS "createdById",proposal.id AS "pendingChangeId",proposal.created_by AS "pendingChangeCreatedById",proposal.proposed_data->>'priceCents' AS "pendingPriceCents",proposal.proposed_data->>'originalPriceCents' AS "pendingOriginalPriceCents" FROM products p LEFT JOIN LATERAL (SELECT id,proposed_data,created_by FROM product_change_proposals WHERE product_id=p.id AND status='pending_review' ORDER BY created_at DESC LIMIT 1) proposal ON true ORDER BY p.updated_at DESC`); res.json({ data: rows }); } catch (error) { next(error); } });
app.get('/api/v1/admin/products/:id/change-history',requirePermission('product:view'),async(req,res,next)=>{try{const id=z.string().uuid().parse(req.params.id);const{rows}=await pool.query(`SELECT pcp.id,pcp.status,pcp.proposed_data->>'priceCents' AS "priceCents",pcp.proposed_data->>'originalPriceCents' AS "originalPriceCents",creator.display_name AS "createdBy",pcp.created_at AS "createdAt",reviewer.display_name AS "reviewedBy",pcp.reviewed_at AS "reviewedAt",pcp.review_note AS "reviewNote" FROM product_change_proposals pcp JOIN users creator ON creator.id=pcp.created_by LEFT JOIN users reviewer ON reviewer.id=pcp.reviewed_by WHERE pcp.product_id=$1 ORDER BY pcp.created_at DESC`,[id]);res.json({data:rows});}catch(error){next(error);}});
app.post('/api/v1/admin/products', requirePermission('product:write'), async (req, res, next) => { const client=await pool.connect(); try { const input = productInput.parse(req.body); const status=input.status==='published'?'pending_review':input.status; await client.query('BEGIN'); const { rows } = await client.query(`INSERT INTO products (sku,name,kind,price_cents,original_price_cents,deposit_cents,available_stock,release_date,image_url,status,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) RETURNING id,status`, [input.sku,input.name,input.kind,input.priceCents,input.originalPriceCents,input.kind === 'preorder' ? input.depositCents : null,input.kind === 'in_stock' ? input.availableStock : null,input.kind === 'preorder' ? input.releaseDate : null,input.imageUrl,status,req.user.id]); await audit(req.user.id,'product.created','product',rows[0].id,input,client); await client.query('COMMIT'); res.status(201).json({ data: rows[0] }); } catch (error) { await client.query('ROLLBACK'); next(error); } finally { client.release(); } });
app.patch('/api/v1/admin/products/:id', requirePermission('product:write'), async (req, res, next) => { const client=await pool.connect(); try { const input = productInput.parse(req.body); await client.query('BEGIN'); const current=await client.query(`SELECT id,status FROM products WHERE id=$1 FOR UPDATE`,[req.params.id]); if(!current.rows[0]) { await client.query('ROLLBACK'); return res.sendStatus(404); } if(current.rows[0].status==='published') { const open=await client.query(`SELECT id FROM product_change_proposals WHERE product_id=$1 AND status='pending_review'`,[req.params.id]); if(open.rows[0]) throw Object.assign(new Error('此商品已有待審變更，請先完成審核。'),{status:409}); const {rows}=await client.query(`INSERT INTO product_change_proposals(product_id,proposed_data,created_by) VALUES($1,$2,$3) RETURNING id,status`,[req.params.id,input,req.user.id]); await audit(req.user.id,'product.change_submitted','product_change',rows[0].id,{productId:req.params.id},client); await client.query('COMMIT'); return res.status(202).json({data:{...rows[0],productId:req.params.id}}); } const status=input.status==='published'?'pending_review':input.status; const { rows } = await client.query(`UPDATE products SET sku=$2,name=$3,kind=$4,price_cents=$5,original_price_cents=$6,deposit_cents=$7,available_stock=$8,release_date=$9,image_url=$10,status=$11,updated_at=now() WHERE id=$1 RETURNING id,status`, [req.params.id,input.sku,input.name,input.kind,input.priceCents,input.originalPriceCents,input.kind === 'preorder' ? input.depositCents : null,input.kind === 'in_stock' ? input.availableStock : null,input.kind === 'preorder' ? input.releaseDate : null,input.imageUrl,status]); await audit(req.user.id,'product.updated','product',rows[0].id,input,client); await client.query('COMMIT'); res.json({ data:rows[0] }); } catch (error) { await client.query('ROLLBACK'); next(error); } finally { client.release(); } });
app.post('/api/v1/admin/products/:id/approve', requirePermission('product:approve'), async (req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const pending=await client.query(`SELECT id,proposed_data,created_by FROM product_change_proposals WHERE product_id=$1 AND status='pending_review' FOR UPDATE`,[req.params.id]);if(pending.rows[0]){if(pending.rows[0].created_by===req.user.id)throw Object.assign(new Error('提案人不可自行核准商品變更。'),{status:403});const v=productInput.parse(pending.rows[0].proposed_data);const {rows}=await client.query(`UPDATE products SET sku=$2,name=$3,kind=$4,price_cents=$5,original_price_cents=$6,deposit_cents=$7,available_stock=$8,release_date=$9,image_url=$10,status='published',updated_at=now() WHERE id=$1 RETURNING id,status`,[req.params.id,v.sku,v.name,v.kind,v.priceCents,v.originalPriceCents,v.kind==='preorder'?v.depositCents:null,v.kind==='in_stock'?v.availableStock:null,v.kind==='preorder'?v.releaseDate:null,v.imageUrl]);if(!rows[0])throw Object.assign(new Error('商品不存在。'),{status:404});await client.query(`UPDATE product_change_proposals SET status='approved',reviewed_by=$2,reviewed_at=now() WHERE id=$1`,[pending.rows[0].id,req.user.id]);await audit(req.user.id,'product.change_approved','product_change',pending.rows[0].id,{productId:req.params.id},client);await client.query('COMMIT');return res.json({data:rows[0]});}const pendingProduct=await client.query(`SELECT created_by FROM products WHERE id=$1 AND status='pending_review' FOR UPDATE`,[req.params.id]);if(!pendingProduct.rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'沒有可核准的商品或價格變更。'});}if(pendingProduct.rows[0].created_by===req.user.id)throw Object.assign(new Error('建立人不可自行核准商品。'),{status:403});const{rows}=await client.query(`UPDATE products SET status='published',updated_at=now() WHERE id=$1 AND status='pending_review' RETURNING id,status`,[req.params.id]);await audit(req.user.id,'product.approved','product',rows[0].id,null,client);await client.query('COMMIT');res.json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.post('/api/v1/admin/products/:id/reject',requirePermission('product:approve'),async(req,res,next)=>{const client=await pool.connect();try{const{reviewNote}=reviewInput.parse(req.body);await client.query('BEGIN');const proposal=await client.query(`SELECT id,created_by FROM product_change_proposals WHERE product_id=$1 AND status='pending_review' FOR UPDATE`,[req.params.id]);if(proposal.rows[0]){if(proposal.rows[0].created_by===req.user.id)throw Object.assign(new Error('提案人不可自行駁回商品變更。'),{status:403});await client.query(`UPDATE product_change_proposals SET status='rejected',reviewed_by=$2,reviewed_at=now(),review_note=$3 WHERE id=$1`,[proposal.rows[0].id,req.user.id,reviewNote]);await audit(req.user.id,'product.change_rejected','product_change',proposal.rows[0].id,{productId:req.params.id,reviewNote},client);await client.query('COMMIT');return res.json({data:{id:req.params.id,status:'published'}});}const product=await client.query(`SELECT created_by FROM products WHERE id=$1 AND status='pending_review' FOR UPDATE`,[req.params.id]);if(!product.rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'沒有可駁回的商品或價格變更。'});}if(product.rows[0].created_by===req.user.id)throw Object.assign(new Error('建立人不可自行駁回商品。'),{status:403});const{rows}=await client.query(`UPDATE products SET status='archived',updated_at=now() WHERE id=$1 AND status='pending_review' RETURNING id,status`,[req.params.id]);await audit(req.user.id,'product.rejected','product',rows[0].id,{reviewNote},client);await client.query('COMMIT');res.json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.post('/api/v1/admin/products/:id/cancel-change',requirePermission('product:write'),async(req,res,next)=>{const client=await pool.connect();try{await client.query('BEGIN');const proposal=await client.query(`SELECT id FROM product_change_proposals WHERE product_id=$1 AND status='pending_review' AND created_by=$2 FOR UPDATE`,[req.params.id,req.user.id]);if(proposal.rows[0]){await client.query(`UPDATE product_change_proposals SET status='cancelled',reviewed_by=$2,reviewed_at=now(),review_note='提案人撤回' WHERE id=$1`,[proposal.rows[0].id,req.user.id]);await audit(req.user.id,'product.change_cancelled','product_change',proposal.rows[0].id,{productId:req.params.id},client);await client.query('COMMIT');return res.json({data:{id:req.params.id,status:'published'}});}const{rows}=await client.query(`UPDATE products SET status='archived',updated_at=now() WHERE id=$1 AND status='pending_review' AND created_by=$2 RETURNING id,status`,[req.params.id,req.user.id]);if(!rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'找不到可撤回的商品或價格變更。'});}await audit(req.user.id,'product.cancelled','product',rows[0].id,null,client);await client.query('COMMIT');res.json({data:rows[0]});}catch(error){await client.query('ROLLBACK');next(error);}finally{client.release();}});
app.get('/api/v1/admin/banners', requirePermission('banner:view'), async (_req, res, next) => {
  try { const { rows } = await pool.query(`SELECT b.id,b.name,b.kind,b.placement,b.priority,b.starts_at AS "startsAt",b.ends_at AS "endsAt",b.target_url AS "targetUrl",b.image_url AS "imageUrl",b.status,u.display_name AS "createdBy",COALESCE(metrics.impressions,0)::int AS impressions,COALESCE(metrics.clicks,0)::int AS clicks FROM banners b JOIN users u ON u.id=b.created_by LEFT JOIN LATERAL (SELECT count(*) FILTER (WHERE event_type='impression') AS impressions,count(*) FILTER (WHERE event_type='click') AS clicks FROM banner_events WHERE banner_id=b.id) metrics ON true ORDER BY b.updated_at DESC`); res.json({ data: rows }); } catch (error) { next(error); }
});
app.post('/api/v1/admin/banners', requirePermission('banner:create'), async (req, res, next) => {
  const client=await pool.connect(); try { const input = bannerInput.parse(req.body); await client.query('BEGIN'); const asset=await client.query(`SELECT public_url FROM banner_assets WHERE object_key=$1 AND status='uploaded' AND created_by=$2`,[input.imageKey,req.user.id]); if(!asset.rows[0]){await client.query('ROLLBACK');return res.status(409).json({error:'請先完成並驗證 Banner 圖片上傳。'});} const { rows } = await client.query(`INSERT INTO banners (name,kind,placement,priority,starts_at,ends_at,target_url,image_key,image_url,status,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,'draft',$10) RETURNING id,status`, [input.name,input.kind,input.placement,input.priority,input.startsAt,input.endsAt,input.targetUrl,input.imageKey,asset.rows[0].public_url,req.user.id]); await audit(req.user.id,'banner.created','banner',rows[0].id,input,client); await client.query('COMMIT'); res.status(201).json({ data: rows[0] }); } catch (error) { await client.query('ROLLBACK');next(error); } finally { client.release(); }
});
app.post('/api/v1/admin/banners/:id/submit', requirePermission('banner:submit'), async (req, res, next) => { try { res.json({ data: await changeState(req.params.id,'draft','pending_review',req.user.id,'banner.submitted') }); } catch (error) { next(error); } });
app.post('/api/v1/admin/banners/:id/approve', requirePermission('banner:approve'), async (req, res, next) => {
  const client=await pool.connect(); try { await client.query('BEGIN'); const { rows } = await client.query(`UPDATE banners SET status=CASE WHEN starts_at > now() THEN 'scheduled'::banner_status ELSE 'published'::banner_status END,approved_by=$2 WHERE id=$1 AND status='pending_review' RETURNING id,status`, [req.params.id,req.user.id]); if (!rows[0]) { await client.query('ROLLBACK'); return res.status(409).json({ error: '只有待審核 Banner 可以發布。' }); } await audit(req.user.id,'banner.approved','banner',rows[0].id,null,client); await client.query('COMMIT'); res.json({ data: rows[0] }); } catch (error) { await client.query('ROLLBACK');next(error); } finally { client.release(); }
});
app.post('/api/v1/admin/banners/:id/disable', requirePermission('banner:disable'), async (req, res, next) => {
  const client=await pool.connect(); try { await client.query('BEGIN'); const { rows } = await client.query(`UPDATE banners SET status='disabled' WHERE id=$1 AND status IN ('draft','pending_review','published','scheduled') RETURNING id,status`, [req.params.id]); if (!rows[0]) { await client.query('ROLLBACK'); return res.status(409).json({ error: 'Banner 無法停用。' }); } await audit(req.user.id,'banner.disabled','banner',rows[0].id,null,client); await client.query('COMMIT'); res.json({ data: rows[0] }); } catch (error) { await client.query('ROLLBACK');next(error); } finally { client.release(); }
});
function requirePermission(permission) { return async (req,res,next) => { try { if ((process.env.AUTH_MODE ?? 'demo') === 'demo') { const role = req.header('x-demo-role') ?? 'admin'; const id = role === 'ad_operator' ? '00000000-0000-0000-0000-000000000002' : role === 'content_editor' ? '00000000-0000-0000-0000-000000000003' : role === 'product_editor' ? '00000000-0000-0000-0000-000000000004' : role === 'consignment_staff' ? '00000000-0000-0000-0000-000000000005' : '00000000-0000-0000-0000-000000000001'; req.user = { id, role }; } else { const subject = await verifyOidcAccessToken(req.header('authorization')); const { rows } = await pool.query('SELECT id,role FROM users WHERE external_subject=$1', [subject]); if (!rows[0]) return res.status(403).json({ error: '此 SSO 帳號尚未獲授權。' }); req.user = rows[0]; } req.user.permissions = roles[req.user.role] ?? []; if (!req.user.permissions.includes(permission)) return res.status(403).json({ error: '權限不足。' }); next(); } catch (error) { next(error); } }; }
async function changeState(id, from, to, actorId, action) { const client=await pool.connect(); try { await client.query('BEGIN'); const { rows } = await client.query('UPDATE banners SET status=$3 WHERE id=$1 AND status=$2 RETURNING id,status', [id,from,to]); if (!rows[0]) { const error = new Error('Invalid state transition'); error.status = 409; throw error; } await audit(actorId,action,'banner',rows[0].id,null,client); await client.query('COMMIT'); return rows[0]; } catch (error) { await client.query('ROLLBACK'); throw error; } finally { client.release(); } }
async function audit(actorId,action,entityType,entityId,payload,executor=pool) { await executor.query('INSERT INTO audit_log (actor_id,action,entity_type,entity_id,payload) VALUES ($1,$2,$3,$4,$5)', [actorId,action,entityType,entityId,payload]); }
function allowPublicConsignment(ip) { const now=Date.now(); const windowMs=60*60*1000; const record=publicSubmissionAttempts.get(ip); const active=record && now-record.startedAt<windowMs ? record : {startedAt:now,count:0}; if(active.count>=5)return false; active.count+=1; publicSubmissionAttempts.set(ip,active); return true; }
function orderIntentExpiresAt() { const minutes=Number(process.env.ORDER_INTENT_TTL_MINUTES ?? 30); if(!Number.isInteger(minutes)||minutes<1||minutes>1440)throw Object.assign(new Error('訂單保留時間設定必須介於 1 至 1440 分鐘。'),{status:503}); return new Date(Date.now()+minutes*60000).toISOString(); }
async function releaseExpiredOrders(actorId) { const client=await pool.connect(); try { await client.query('BEGIN'); const {rows:orders}=await client.query(`SELECT id,order_number FROM orders WHERE status='pending_payment' AND expires_at<=now() FOR UPDATE SKIP LOCKED LIMIT 100`); for(const order of orders){const{rows:items}=await client.query(`SELECT product_id,SUM(quantity)::int AS quantity FROM order_items WHERE order_id=$1 AND reserved_stock=true GROUP BY product_id`,[order.id]);for(const item of items)await client.query(`UPDATE products SET available_stock=available_stock+$2 WHERE id=$1`,[item.product_id,item.quantity]);await client.query(`UPDATE orders SET status='expired',reservation_released_at=now(),updated_at=now() WHERE id=$1 AND status='pending_payment'`,[order.id]);await client.query(`INSERT INTO audit_log(actor_id,action,entity_type,entity_id,payload) VALUES($1,'order.expired','order',$2,$3)`,[actorId,order.id,{orderNumber:order.order_number,stockReleased:true}]);}await client.query('COMMIT');return{released:orders.length};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();} }
app.use((error,_req,res,_next) => { if (error instanceof z.ZodError) return res.status(400).json({ error: '請檢查欄位內容。', details: error.flatten() }); console.error(error); const status=error.status ?? 500; res.status(status).json({ error: status < 500 || status === 503 ? error.message : '伺服器發生錯誤。' }); });
app.listen(process.env.PORT ?? 3000, () => console.log('jiangnan-card-api listening'));
